#!/bin/bash
   
for barcode in "A1 TAAGGCGA_ATAGAGAG" "A2 CGTACTAG_ATAGAGAG" "A3 AGGCAGAA_ATAGAGAG" "A4 TCCTGAGC_ATAGAGAG" "A5 GGACTCCT_ATAGAGAG" "A6 TAGGCATG_ATAGAGAG" "A7 CTCTCTAC_ATAGAGAG" "A8 CGAGGCTG_ATAGAGAG" "A9 AAGAGGCA_ATAGAGAG" "A10 GTAGAGGA_ATAGAGAG" "A11 GCTCATGA_ATAGAGAG" "A12 ATCTCAGG_ATAGAGAG" "B1 TAAGGCGA_AGAGGATA" "B2 CGTACTAG_AGAGGATA" "B3 AGGCAGAA_AGAGGATA" "B4 TCCTGAGC_AGAGGATA" "B5 GGACTCCT_AGAGGATA" "B6 TAGGCATG_AGAGGATA" "B7 CTCTCTAC_AGAGGATA" "B8 CGAGGCTG_AGAGGATA" "B9 AAGAGGCA_AGAGGATA" "B10 GTAGAGGA_AGAGGATA" "B11 GCTCATGA_AGAGGATA" "B12 ATCTCAGG_AGAGGATA" "C1 TAAGGCGA_CTCCTTAC" "C2 CGTACTAG_CTCCTTAC" "C3 AGGCAGAA_CTCCTTAC" "C4 TCCTGAGC_CTCCTTAC" "C5 GGACTCCT_CTCCTTAC" "C6 TAGGCATG_CTCCTTAC" "C7 CTCTCTAC_CTCCTTAC" "C8 CGAGGCTG_CTCCTTAC" "C9 AAGAGGCA_CTCCTTAC" "C10 GTAGAGGA_CTCCTTAC" "C11 GCTCATGA_CTCCTTAC" "C12 ATCTCAGG_CTCCTTAC" "D1 TAAGGCGA_TATGCAGT" "D2 CGTACTAG_TATGCAGT" "D3 AGGCAGAA_TATGCAGT" "D4 TCCTGAGC_TATGCAGT" "D5 GGACTCCT_TATGCAGT" "D6 TAGGCATG_TATGCAGT" "D7 CTCTCTAC_TATGCAGT" "D8 CGAGGCTG_TATGCAGT" "D9 AAGAGGCA_TATGCAGT" "D10 GTAGAGGA_TATGCAGT" "D11 GCTCATGA_TATGCAGT" "D12 ATCTCAGG_TATGCAGT" "E1 TAAGGCGA_TACTCCTT" "E2 CGTACTAG_TACTCCTT" "E3 AGGCAGAA_TACTCCTT" "E4 TCCTGAGC_TACTCCTT" "E5 GGACTCCT_TACTCCTT" "E6 TAGGCATG_TACTCCTT" "E7 CTCTCTAC_TACTCCTT" "E8 CGAGGCTG_TACTCCTT" "E9 AAGAGGCA_TACTCCTT" "E10 GTAGAGGA_TACTCCTT" "E11 GCTCATGA_TACTCCTT" "E12 ATCTCAGG_TACTCCTT" "F1 TAAGGCGA_AGGCTTAG" "F2 CGTACTAG_AGGCTTAG" "F3 AGGCAGAA_AGGCTTAG" "F4 TCCTGAGC_AGGCTTAG" "F5 GGACTCCT_AGGCTTAG" "F6 TAGGCATG_AGGCTTAG" "F7 CTCTCTAC_AGGCTTAG" "F8 CGAGGCTG_AGGCTTAG" "F9 AAGAGGCA_AGGCTTAG" "F10 GTAGAGGA_AGGCTTAG" "F11 GCTCATGA_AGGCTTAG" "F12 ATCTCAGG_AGGCTTAG" "G1 TAAGGCGA_ATTAGACG" "G2 CGTACTAG_ATTAGACG" "G3 AGGCAGAA_ATTAGACG" "G4 TCCTGAGC_ATTAGACG" "G5 GGACTCCT_ATTAGACG" "G6 TAGGCATG_ATTAGACG" "G7 CTCTCTAC_ATTAGACG" "G8 CGAGGCTG_ATTAGACG" "G9 AAGAGGCA_ATTAGACG" "G10 GTAGAGGA_ATTAGACG" "G11 GCTCATGA_ATTAGACG" "G12 ATCTCAGG_ATTAGACG" "H1 TAAGGCGA_CGGAGAGA" "H2 CGTACTAG_CGGAGAGA" "H3 AGGCAGAA_CGGAGAGA" "H4 TCCTGAGC_CGGAGAGA" "H5 GGACTCCT_CGGAGAGA" "H6 TAGGCATG_CGGAGAGA" "H7 CTCTCTAC_CGGAGAGA" "H8 CGAGGCTG_CGGAGAGA" "H9 AAGAGGCA_CGGAGAGA" "H10 GTAGAGGA_CGGAGAGA" "H11 GCTCATGA_CGGAGAGA" "H12 ATCTCAGG_CGGAGAGA"
    
 do
  set -- $barcode
  echo $1
  cat ?_HTT7NBGXB.?.$2.unmapped.1.fastq.gz > $PWD/MergedFiles/comb$1.1.fastq.gz
  cat ?_HTT7NBGXB.?.$2.unmapped.2.fastq.gz > $PWD/MergedFiles/comb$1.2.fastq.gz
done
   
exit 0

